services:
  simpleaiapi:
    image: ghcr.io/borik007/simpleaiapi:latest
    container_name: simpleaiapi
    restart: on-failure
    build:
      context: .
      dockerfile: SimpleAIAPI/Dockerfile
    environment:
      - CHAT_HISTORY_SIZE=10
      - CACHE_SIZE=10
      - OLLAMA_IP=ollama:11434
      - ConnectionStrings__DefaultConnection=Host=db;Database=ai_db;Username=postgres;Password=postgres
    depends_on:
      - db
      - ollama
    ports:
      - "8080:8080"

  db:
    image: postgres:18-alpine 
    container_name: db
    environment:
      - POSTGRES_DB=ai_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11435:11434"

volumes:
  ollama_data:
